public enum ApprovalServiceOperation: String, CaseIterable, Sendable {
    case gitHelperVersion = "git-helper-version"
    case gitRegister = "git-register"
    case gitUnregister = "git-unregister"
    case uvHelperVersion = "uv-helper-version"
    case uvRegister = "uv-register"
    case uvGet = "uv-get"
    case awsHelperVersion = "aws-helper-version"
    case dockerHelperVersion = "docker-helper-version"
    case goatHelperVersion = "goat-helper-version"
    case ordercliHelperVersion = "ordercli-helper-version"
    case openhueHelperVersion = "openhue-helper-version"
    case plumberHelperVersion = "plumber-helper-version"
    case uaaHelperVersion = "uaa-helper-version"
    case railwayHelperVersion = "railway-helper-version"
    case oxideHelperVersion = "oxide-helper-version"
    case fastlyHelperVersion = "fastly-helper-version"
    case sqlcmdHelperVersion = "sqlcmd-helper-version"
    case terraformHelperVersion = "terraform-helper-version"
    case aliyunHelperVersion = "aliyun-helper-version"
    case wakatimeHelperVersion = "wakatime-helper-version"
    case rcloneHelperVersion = "rclone-helper-version"
    case kubectlHelperVersion = "kubectl-helper-version"
    case inject
    case injectFd = "inject-fd"
    case varlock
    case keys
    case authorize
    case gpgSign = "gpg-sign"
    case sshSign = "ssh-sign"
    case sshIdentities = "ssh-identities"
    case proxyStart = "proxy-start"
    case awsCredentials = "aws-credentials"
    case dockerGet = "docker-get"
    case goatGet = "goat-get"
    case ordercliGet = "ordercli-get"
    case openhueGet = "openhue-get"
    case plumberGet = "plumber-get"
    case uaaGet = "uaa-get"
    case railwayGet = "railway-get"
    case oxideGet = "oxide-get"
    case fastlyGet = "fastly-get"
    case sqlcmdGet = "sqlcmd-get"
    case terraformGet = "terraform-get"
    case aliyunGet = "aliyun-get"
    case wakatimeGet = "wakatime-get"
    case rcloneGet = "rclone-get"
    case kubectlGet = "kubectl-get"
    case dockerSave = "docker-save"
    case dockerDelete = "docker-delete"
    case goatSave = "goat-save"
    case goatDelete = "goat-delete"
    case ordercliSave = "ordercli-save"
    case ordercliDelete = "ordercli-delete"
    case openhueSave = "openhue-save"
    case plumberSave = "plumber-save"
    case uaaSave = "uaa-save"
    case uaaDelete = "uaa-delete"
    case railwaySave = "railway-save"
    case railwayDelete = "railway-delete"
    case oxideSave = "oxide-save"
    case oxideDelete = "oxide-delete"
    case fastlySave = "fastly-save"
    case fastlyDelete = "fastly-delete"
    case sqlcmdSave = "sqlcmd-save"
    case sqlcmdDelete = "sqlcmd-delete"
    case terraformSave = "terraform-save"
    case terraformDelete = "terraform-delete"
    case list
    case history
    case historyWindow = "history-window"
    case historyRead = "history-read"
    case historyNext = "history-next"
    case save
    case saveIfAbsentOrEqual = "save-if-absent"
    case bless
    case delete
    case openWindow = "open-window"
    case wranglerSave = "wrangler-save"
    case wranglerDelete = "wrangler-delete"
    case ghSave = "gh-save"
    case ghDelete = "gh-delete"
    case stripeSave = "stripe-save"
    case stripeDelete = "stripe-delete"

    public var disclosesProtectedMetadata: Bool {
        self == .list || self == .history || self == .historyWindow
            || self == .historyRead || self == .historyNext
    }
}
